### ISSUE TITLE
[rviz_tactile_plugin] contacts stored forever, show wrong display on clock loop

### ISSUE THREAD

**Issue by guihomework** [ubi-agni/tactile_toolbox#9]
In the case of playing bag files with clock publishing and loop option, the clock jumps back in time, making the stored contacts at the end of the loop appear at the start of the loop even if there is no new data yet for those contacts.

Even worse. If there is no data published at all on contact_states in the second loop, (see video and terminal showing no data published) the simple fact that the clock loops shows past data the re-become valid for a while. 

see video [remaining_arrows_loop.mp4.zip](https://github.com/ubi-agni/tactile_toolbox/files/5335009/remaining_arrows_loop.mp4.zip)

A solution could be to clear the contact buffer if a jumbpack in time is detected.

**Comment by rhaschke** [comment]
I guess this requires `sim_time` to be configured? @guihomework, could you please provide (via email) a rosbag file to reproduce this (and test a fixup)?

**Comment by guihomework** [comment]
I tried to do so, but the bagfiles I have have to many data to clearly see the problem, I will need to create a fake one with several rostopic echo in a row, while keeping a /tf up to data too. stay tunes
